### ISSUE TITLE
Add Collabora Online integration

### ISSUE THREAD

**Issue by sandersoft** [nextcloud/nextcloud-snap#104]
Collabora Online integration would be nice feature to have

https://nextcloud.com/collaboraonline/

**Comment by kyrofa** [comment]
My impression is that this has nothing to do with the snap-- install the app and point it to your Collabora server. If you want Collabora snapped, that's a different matter :smile: . Please re-open if I'm wrong.

**Comment by enoch85** [comment]
> If you want Collabora snapped

Yes please :)

**Comment by oparoz** [comment]
> Yes please :)

What are the advantages compared to the docker?

**Comment by enoch85** [comment]
Dunno as I haven't looked it up. But snap is built in Ubuntu and we could ship it with the VM in the same way as we do with SpreedMe. It could also be integrated in the Nextcloud Box.

**Comment by oparoz** [comment]
> But snap is built in Ubuntu and we could ship it with the VM in the same way as we do with SpreedMe.

For Spreed.ME it makes sense to use a snap because the docker compiles the app, but for collabora, it just pulls binaries iirc.

> It could also be integrated in the Nextcloud Box. 

Forget about that idea. Not with a Pi2 with 1GB of RAM which is already running Nextcloud. Look at the time it takes to process pictures.
You'd be better off setting up a pcengine box with just collabora on it.

And so many things don't work properly in snaps today that I don't expect Collabora Office to run as-is. It would probably require lots of patches, hacks, command line commands, etc.

**Comment by enoch85** [comment]
> Forget about that idea.

It's forgotten, wasn't thinking about that it actually was a rPi2.

> just pulls binaries iirc.

I don't know how Collabora is built but @ezraholm50 talked about that it was buggy (the docker image) and I'd rather use something that is made by Nextclouders

**Comment by skollrc** [comment]
Hi everyone, 

I would like to know how to integrate collabora online in a snap or if it already exist?
