### ISSUE TITLE
Local External Storage can't mount other directory

### ISSUE THREAD

**Issue by lswymxk** [nextcloud/nextcloud-snap#1082]
Hi,
 I installed nextcloud with snap successfully，but when I set local external storage with web, I can't  mount other directory . my server is openmediavault（debian9). I mount hard disk  at the directory "/srv/disk1". When I set external storage  configuration in the directory "/srv", the local external storage file page shows "You don't have permission to upload and creat files here", and I can't see any files. How can I do to mount the directory "/srv/disk1" in local external storage?

**Comment by lu4p** [comment]
You can probably only connect drives mounted in /media.

-------From the README -------
Removable media

Also note that the interface providing the ability to access removable media is not automatically connected upon install, so if you'd like to use external storage (or otherwise use a device in /media for data), you need to give the snap permission to access removable media by connecting that interface:

$ sudo snap connect nextcloud:removable-media

**Comment by kyrofa** [comment]
@lu4p is correct.
