### ISSUE TITLE
Where is the news app

### ISSUE THREAD

**Issue by burdickjp** [nextcloud/nextcloud-snap#124]
I just installed the snap and I'm having trouble finding the news app, or where I'd want to install it if I were to do so manually. is there a problem between the news app and the current version of nextcloud?

**Comment by MariusBluem** [comment]
Hi there :) This is unrelated to the `nextcloud-snap` because this is unfortunately happening on other Nextcloud appliances and servers too 😉 The `news` app is not longer published on the ownCloud appstore which is in use in Nextcloud 10 ... With Nextcloud 11 we will start to use our own appstore ([apps.nextcloud.com](apps.nextcloud.com)) which is currently in beta ... I don't know about the exactly reasons of the deletion of `news` from the ownCloud appstore ... 

You may want to manually download Nextcloud News from ([apps.nextcloud.com](github.com/nextcloud/news)) or the repository ([github.com/nextcloud/news](github.com/nextcloud/news)) and install it by putting it into the apps/ directory of your Nextcloud instance ... Then you need to activate it on your apps-page 😄 

If you need more help, feel free to use our forums ([help.nextcloud.com](help.nextcloud.com)) or the issue tracker of the news-app ([github.com/nextcloud/news/issues](github.com/nextcloud/news/issues))

@BernhardPosselt

**Comment by BernhardPosselt** [comment]
You can switch to the new app store and install it from there check the forums
