### ISSUE TITLE
Waiting for PHP Nextcloud Snap

### ISSUE THREAD

**Issue by BonziBuddyMonkey** [nextcloud/nextcloud-snap#1246]
Hi. I have run into a problem with my Nextcloud snap on Ubuntu 18. It worked fine a couple of days ago. I keep getting error 503, though it says all services are running. But when I run the debugging it gets stuck at "Waiting for PHP". I have tried:
1. Restarting, disable&enable 
2. Search for updates
3. Restartet the server 
4. And I even recovered it from a one week old backup but it ended the same way.

I am clueless to what is causing this. 

[Redis.txt](https://github.com/nextcloud/nextcloud-snap/files/4182074/Redis.txt)
[PHP.txt](https://github.com/nextcloud/nextcloud-snap/files/4182076/PHP.txt)
[Nextcloud.renew.txt](https://github.com/nextcloud/nextcloud-snap/files/4182077/Nextcloud.renew.txt)
[MySQL.txt](https://github.com/nextcloud/nextcloud-snap/files/4182078/MySQL.txt)
[mDNS Publisher.txt](https://github.com/nextcloud/nextcloud-snap/files/4182079/mDNS.Publisher.txt)
[fixer.txt](https://github.com/nextcloud/nextcloud-snap/files/4182081/fixer.txt)
[cron.txt](https://github.com/nextcloud/nextcloud-snap/files/4182082/cron.txt)
[Apache.txt](https://github.com/nextcloud/nextcloud-snap/files/4182083/Apache.txt)

Any Ideers ? Btw its running on a ESXI 6.5 HP G8

Hope you guys can get anything out of this.

**Comment by kyrofa** [comment]
> when I run the debugging it gets stuck at "Waiting for PHP"

What are you actually doing to debug where you're seeing this error? How long have you let it sit? I don't see any immediately obvious issues-- PHP looks like it's firing up fine, for example. Can you please show us the contents of `<data dir>/nextcloud.log` (by default `/var/snap/nextcloud/common/nextcloud/data/nextcloud.log` unless you changed it) and `/var/snap/nextcloud/current/apache/logs/php_errors.log` and finally `/var/snap/nextcloud/current/php/php-fpm.log`, please?

**Comment by BonziBuddyMonkey** [comment]
Hi. Thank you for your answer ! I ran the error script from this site: https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts And kept getting stuck on "Waiting for PHP" I gave it a good 10 minuttes before concluding it was not going to finish.

I'm sorry  for the lag of info, but I have become quite frustrated with this. I have collected the logs you suggested, though I do think there is something very wrong in the data base, as it complains about not being able to connect to it in the PHP error log. But I have never seen that error before.

Attached files: 
[PHPError.txt](https://github.com/nextcloud/nextcloud-snap/files/4182608/PHPError.txt)
[php-fpm.txt](https://github.com/nextcloud/nextcloud-snap/files/4182609/php-fpm.txt)
[NextcloudLog.txt](https://github.com/nextcloud/nextcloud-snap/files/4182610/NextcloudLog.txt)

**Comment by kyrofa** [comment]
You're right. Let's see the output of `/var/snap/nextcloud/current/mysql/error.log`, please.

**Comment by BonziBuddyMonkey** [comment]
Yeah lets have a look. Thank you for your help btw !
I have the file right here: 
[Mysql.txt](https://github.com/nextcloud/nextcloud-snap/files/4182779/Mysql.txt)

**Comment by kyrofa** [comment]
Hmm, I haven't seen this:

> 2020-02-10T17:29:25.934775Z 0 [ERROR] Fatal error: Can't open and lock privilege tables: Incorrect file format 'user'
> 2020-02-10T17:29:25.934808Z 0 [ERROR] Fatal error: Failed to initialize ACL/grant/time zones structures or failed to remove temporary table files.
> 2020-02-10T17:29:25.934897Z 0 [ERROR] Aborting

**Comment by kyrofa** [comment]
Can I see the output of `snap version`, please?

**Comment by BonziBuddyMonkey** [comment]
Hi its right here: 

Name       Version      Rev    Tracking  Publisher   Notes
core       16-2.42.5    8268   stable    canonical✓  core
nextcloud  16.0.8snap1  18885  stable    nextcloud✓  -

```

**Comment by BonziBuddyMonkey** [comment]
Sorry forgot to add the version: 

```
snap    2.42.5
snapd   2.42.5
series  16
ubuntu  18.04
kernel  4.15.0-76-generic
```

**Comment by kyrofa** [comment]
Alright it sounds like you have some corrupted tables, perhaps due to a power loss. Do you feel comfortable trying something like [this](https://stackoverflow.com/questions/28521530/mysql-fatal-error-cant-open-and-lock-privilege-tables-incorrect-file-format)? It sounds like you have a recent backup?

**Comment by BonziBuddyMonkey** [comment]
I have a backup from 55 days ago, I will try that. But my hopes are not that high as it failed with the other backup from a week ago. I would be okay with trying the link suggested, but it im not sure how upgrade the database when its running as a snap .

**Comment by BonziBuddyMonkey** [comment]
Its working again with the 55 days old backup. But im not sure how it happend in the first place. There isnt anything that got lost in the backup so thank god for that. But im unsure if this could have something to do with the hardware?

**Comment by kyrofa** [comment]
It's certainly possible that your hardware is failing, although it's hard to know. Check your smart status and run some tests. I'm glad you're back up and running, though! I'll go ahead and close this issue, although feel free to continue discussion here.

**Comment by DatGeekUKnow** [comment]
> Alright it sounds like you have some corrupted tables, perhaps due to a power loss. Do you feel comfortable trying something like [this](https://stackoverflow.com/questions/28521530/mysql-fatal-error-cant-open-and-lock-privilege-tables-incorrect-file-format)? It sounds like you have a recent backup?

Hey there! I'm having a similar issue, and I think it may be due to corrupted table data.  I checked out the link you referenced, but I'm unsure as to how I can apply it within the snap environment (since the host machine doesn't have mysql or mariadb installed)
Any quick tips on applying the linked changes within the snap environment?

**Comment by aquananu** [comment]
hi community

need your support

yesterday i had installed phpmyadmin on the system running nextcloud SNAP 24.04 on ubuntu 22.04, the installation failed and then i removed the phpmyadmin and purged the same also.

since then the nextcloud is not working, 

getting **waiting for php** when running command sudo nextcloud.occ maintainence:repair

below is output of command : - snap services | grep active

canonical-livepatch.canonical-livepatchd  enabled  active    -
docker.dockerd                            enabled  active    -
lxd.activate                              enabled  inactive  -
lxd.daemon                                enabled  inactive  socket-activated
lxd.user-daemon                           enabled  inactive  socket-activated
nextcloud.apache                          enabled  active    -
nextcloud.logrotate                       enabled  inactive  timer-activated
nextcloud.mdns-publisher                  enabled  active    -
nextcloud.mysql                           enabled  active    -
nextcloud.nextcloud-cron                  enabled  active    -
nextcloud.nextcloud-fixer                 enabled  active    -
nextcloud.php-fpm                         enabled  active    -
nextcloud.redis-server                    enabled  active    -
nextcloud.renew-certs                     enabled  active    -

command : sudo systemctl status snap.nextcloud.apache
● snap.nextcloud.apache.service - Service for snap application nextcloud.apache
     Loaded: loaded (/etc/systemd/system/snap.nextcloud.apache.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-09-30 09:24:32 IST; 4h 12min ago
   Main PID: 1065787 (run-httpd)
      Tasks: 3 (limit: 4568)
     Memory: 1.1M
        CPU: 15.946s
     CGroup: /system.slice/snap.nextcloud.apache.service
             ├─1065787 /bin/sh /snap/nextcloud/31563/bin/run-httpd -k start -DFOREGROUND
             ├─1065820 /bin/sh /snap/nextcloud/31563/bin/setup-nextcloud
             └─1623399 sleep 1

Sep 30 09:24:32 ub22 systemd[1]: Started Service for snap application nextcloud.apache.
Sep 30 09:24:32 ub22 nextcloud.apache[1065787]: Making sure nextcloud is setup...
Sep 30 09:24:32 ub22 nextcloud.apache[1065820]: Waiting for PHP...

even this one
navneet@ub22:/var/snap$ sudo nextcloud.occ status
Waiting for PHP... 

no errors are being listed in the 
nextcloud log 
mysql log 
redis log


Kindly advise what could be the reason for apache waiting for php
