### ISSUE TITLE
[Question]How to change datadirectory to a non-media/mnt path?

### ISSUE THREAD

**Issue by GoldJohnKing** [nextcloud/nextcloud-snap#1305]
Hi, I had installed nextcloud 14 via snap on Debian 9 and set the datadirectory to `/root/external_disk`, I upgraded all the way, it works without any error.

However, I'm trying to make a fresh install of nextcloud 17 via snap on Ubuntu 18.04.4. When I set the datadirectory to `/root/external_disk`, the web page gives me "There's no .ocdata file." error.

I'm pretty sure my older server could access to the `/root/external_disk` without any problem, but the newer cant.

I have followed this when configuring the new one, and the old one (as I remembered): https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition

I've struggled for 3 days, googled all where but still not come up with an idea. Did I miss something when configuring the new one or the support of other directory access has gone?

Thanks for your help in advance!

**Comment by kyrofa** [comment]
I believe that may have worked on Debian because Debian doesn't support the confinement technology required by snaps, and thus snaps run mostly unconfined there. The Nextcloud snap has never actually supported accessing data there in a confined manner, and on Ubuntu that matters. The `removable-media` plug only covers `/media` and `/mnt`.

**Comment by GoldJohnKing** [comment]
Okay, that's it...
Thanks a lot for your reply!
