### ISSUE TITLE
Can't Access OnlyOffice

### ISSUE THREAD

**Issue by hexydes** [nextcloud/nextcloud-snap#1316]
#### Describe the bug
NextCloud appears to have updated itself to version 18 last night (yay!). However, I'm unable to access the functions of OnlyOffice. I read [here](https://www.techrepublic.com/article/how-to-enable-the-onlyoffice-document-server-in-nextcloud-18/) that it might be an issue with NextCloud, and you have to install "Community Document Server" to get the changes to pick up. I'm also unable to install that (if that is indeed a needed step) because of limited memory in php.ini (which appears to be read-only in the Snap?).

#### To Reproduce
1. Go to NextCloud.
2. Click on '+ sign' for new item.
3. Document, Spreadsheet, Presentation, etc are not available options.

#### Expected behavior
I would expect to see these options available, since my installation is now on version 18. Possible there is a bug in NextCloud that prevents this from happening, and when I try to install Community Document Server to get around it, I receive 

Error | PHP | Allowed  memory size of 134217728 bytes exhausted (tried to allocate 315857416  bytes) at /snap/nextcloud/20498/htdocs/lib/private/Installer.php#285

#### OS/snapd/snap version
What OS and version are you running? Ubuntu 18.04, NextCloud 18.0.4.

#### Logs
N/A

**Comment by kyrofa** [comment]
Indeed, while v18 offers the ability to install recommended apps (including OnlyOffice) to users who are freshly installing it, users that upgrade to v18 are left to do this on their own (a lot of people including myself would be unhappy if such things were thrust upon us in an upgrade without option).

Please see [this comment](https://github.com/nextcloud/nextcloud-snap/issues/1313#issuecomment-619382764) for some workarounds to the timeout issue (basically: install from cli instead of from the web).
