### ISSUE TITLE
slow sync for small files, change my.cnf values

### ISSUE THREAD

**Issue by Guillaume99** [nextcloud/nextcloud-snap#132]
as per https://github.com/owncloud/core/issues/20967#issuecomment-205474772
add the following values in my.cnf to increase sync speed on small files:

innodb_buffer_pool_size = 512M
innodb_buffer_pool_instance = 1
innodb_flush_log_at_trx_commit = 2
innodb_log_buffer_size = 32M
innodb_max_dirty_pages_pct = 90

**Comment by oparoz** [comment]
From the same post

>There is a risk data loss when the system crashes. More reports on this modification (one user wasn't able to restore the database after a hard-reset of his system)

Is suspect this comes from `innodb_flush_log_at_trx_commit = 2`

Could you test without to see what sort of gains you still get?

**Comment by cherokee1** [comment]
Guys, please help me, How i can modify httpd.conf or my.cnf
I have 2 ip address, and want specify only one for apache running in snap.
What is true way :) ?

**Comment by aronovgj** [comment]
I'm pretty sure that the speedup is due to `innodb_flush_log_at_trx_commit = 2`. This however violates ACID so that is not a solution. It has to be fixed differently. I have the same issue not using snap. I have been constantly fighting it since I started using Owncloud 8. I think this setting messed up my database a lot of times, creating locking issues and stuff like that.

Another workaround I found is to change some tables to MYISAM. Has anyone tried it?
https://forum.owncloud.org/viewtopic.php?t=30083#p119093

**Comment by oparoz** [comment]
> Another workaround I found is to change some tables to MYISAM. Has anyone tried it?
https://forum.owncloud.org/viewtopic.php?t=30083#p119093

That's interesting. Could you ask in [our forums](https://help.nextcloud.com/c/support) so that more MySQL experts could participate in the discussion?

**Comment by aronovgj** [comment]
here? :)
https://help.nextcloud.com/t/slow-synchronisation-between-desktop-client-and-server/5090/8?u=aronovgj

**Comment by aronovgj** [comment]
I reset my db (fighting locking issues, probably caused by redis) and converted oc_activity, oc_filecache and oc_file_locks. The improvement seems not to be as big as with `innodb_flush_log_at_trx_commit = 2` but it is comparable. It makes my server usable again and the HDD is not at 100% I/O anymore.

The commands are:
```
ALTER TABLE oc_activity ENGINE = MyISAM;
ALTER TABLE oc_file_locks ENGINE = MyISAM;
ALTER TABLE oc_filecache ENGINE = MyISAM;
```

Please note that I have no idea what I am doing and that by doing this you could cause armageddon

**Comment by kyrofa** [comment]
> There is a risk data loss when the system crashes. More reports on this modification (one user wasn't able to restore the database after a hard-reset of his system)

Yeah... not sure we want to enable such things here. We want to make sure we know what we're doing!
