### ISSUE TITLE
Ldap Error

### ISSUE THREAD

**Issue by EvgeniyShell** [nextcloud/nextcloud-snap#1391]
Hello.
After Automatic update, something went wrong with ldap, I have infinite users paging)) log:

Error | user_ldap | Attempt for Paging? 1 
Error | PHP | ldap_search(): Search: Critical extension is unavailable at /snap/nextcloud/21796/htdocs/apps/user_ldap/lib/LDAP.php#341

**Comment by kyrofa** [comment]
First of all, to get back to v18 run `sudo snap revert nextcloud`. I'm afraid this sounds like an issue with upstream Nextcloud, can you please [log an issue there](https://github.com/nextcloud/server)? I saw a forum post about this as well, but it's since been deleted which isn't helpful ([here's the google cache](https://webcache.googleusercontent.com/search?q=cache:q2KyG9cB_P4J:https://help.nextcloud.com/t/error-ldap-search-search-critical-extension-is-unavailable-at-var-www-nextcloud-apps-user-ldap-lib-ldap-php-341/84915+&cd=1&hl=en&ct=clnk&gl=us&client=ubuntu) of it).
