### ISSUE TITLE
Update to Nextcloud 11

### ISSUE THREAD

**Issue by kristbaum** [nextcloud/nextcloud-snap#143]
Nextcloud 11 is out, and brings a ton of new features \o/
https://nextcloud.com/blog/nextloud-11-sets-new-standard-for-security-and-scalability/

**Comment by kyrofa** [comment]
@kristbaum this has now been fixed in `develop`; as soon as [the builds](https://code.launchpad.net/~nextcloud-snappy-dev/+snap/nextcloud-candidate) finish it'll be in the candidate channel. Would you mind taking it for a spin and make sure the features work as expected?

    $ sudo snap install --candidate nextcloud

Or if you already have it installed (not recommended for production systems):

    $ sudo snap refresh --candidate nextcloud

**Comment by kristbaum** [comment]
Thanks, will test it now, I'll report back if I find something

**Comment by kristbaum** [comment]
The Version for candidate is still 10.0.2, gonna try it again in a few hours :)

**Comment by kyrofa** [comment]
Note that the version shown in `snap list` will still be 10.0.2, but you'll see 11 in the admin interface. However, yes, the builds have not yet completed. I'll keep an eye on them and comment here when they have.

**Comment by kyrofa** [comment]
Alright, the builds are complete.

**Comment by flexiondotorg** [comment]
I just updated to Nextcloud 11 via the candidate release channel. I've noticed Documents and Tasks can  no longer be enabled, they both claim:

> This app has no minimum Nextcloud version assigned. This will cause an error in the future. This app cannot be installed because the following dependencies are not fulfilled: Server version 9.2 or lower is required.

**Comment by kyrofa** [comment]
Thanks for the heads up @flexiondotorg! I've verified that the Contacts and Calendar apps make it through okay, but I don't want to roll out an automatic update that disable people's apps. I'll hold off on migrating this to the stable channel until the app developers catch up (or until I can verify that the app developers don't intend to catch up).

**Comment by kristbaum** [comment]
I did a new install, and can confirm @flexiondotorg. Both apps are missing from the appstore. All others seem to work just fine.

**Comment by kristbaum** [comment]
When I try to open .odt files, I get "Access Denied", this is probably related to the missing documents app. But all in all this Nextcloud release works great. I've tried the 2FA, Video Calls, Global Address Book, the Mail app and a few more, and the all worked great. When the Document and Tasks Situation is resolved I'm looking forward to an awesome release.

**Comment by Guillaume99** [comment]
maybe you should wait a little ...
https://help.nextcloud.com/t/tasks-app-for-nextcloud-11/6138
https://help.nextcloud.com/t/https-nextcloud-mysite-org-data-ocdata-t-1481715120916-403-forbidden/6175
https://help.nextcloud.com/t/creating-users-doesnt-work-properly/6171
https://help.nextcloud.com/t/nc11-file-move-error-issue/6161
https://help.nextcloud.com/t/redirect-loop-in-nc11/6155
...

**Comment by kristbaum** [comment]
@kyrofa maybe you could put Nextcloud 11 in the beta channel for now, and wait until some bugs are fixed?

**Comment by kyrofa** [comment]
Thanks for the input everyone! Indeed, I'll hold off on this for now. @kristbaum that's a good idea, I'll see if I can go ahead and change the daily builds in beta to be taken from stable11, though candidate will stay on v11 as well.

**Comment by kyrofa** [comment]
@flexiondotorg looks like the Tasks app at least has been updated. Can you please re-run your test?

**Comment by JoshPiebuntu** [comment]
I noticed docs were disabled, and thought it was perhaps a push to Collabora.  It did motivate me to attempt integrating Collabora 3 times now onto my Snap install.  I understand that is impossible due to unwriteable parts of the Snap, correct?

Per chance, does anyone have a US West Coast based Collabora/Nextcloud I could take for a demo user credentials spin?  Type lag on Collabora's demo UK server is almost unuseably slow from the SF Bay Area.   

Thanks to anyone, and everyone who has contributed to Nextcloud.  It is amazing.

**Comment by kyrofa** [comment]
@JoshPiebuntu I'm not so sure it's a push to Collabora, but unlike Tasks (which is published by a third-party developer), Documents [seems to be developed by ownCloud](https://apps.owncloud.com/content/show.php/Documents?content=168711). It's not in the Nextcloud store, so perhaps they haven't ported it. Though of course, perhaps they haven't ported it because of Collabora. Given [this thread](https://help.nextcloud.com/t/nc11-documents-app/6359) about it, I'm starting to feel that Nextcloud 11 should be released to stable.

I've not investigated integrating Collabora into the snap, though I suspect it would need to be its own snap.

**Comment by kyrofa** [comment]
Alright I'm going to start the process of releasing v11 into stable. If anyone has any objections please raise them now.

**Comment by mguazzardo** [comment]
Maybe , that script could help anyone.
I used in my home install. Note. The lab lacks of ldap and ssl support.

https://github.com/mguazzardo/collabora-Snap/wiki
