### ISSUE TITLE
Option to move MySQL data directory to a different location

### ISSUE THREAD

**Issue by dniku** [nextcloud/nextcloud-snap#1444]
Currently, MySQL data directory is located under `/var/snap/nextcloud/current/mysql/`. I have not found a way to configure its location (unlike the location of the Nextcloud data directory, whose configuration is [documented](https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition)). This could be useful in order to e.g. move it to an external HDD drive and prevent the SD card degradation.

```bash
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  19.0.1snap3  22654  latest/stable  nextcloud✓  -
$ snap version
snap      2.45.3.1
snapd     2.45.3.1
series    16
raspbian  10
kernel    4.19.118-v7+
```

**Comment by kyrofa** [comment]
The problem is that, unlike the Nextcloud data, the MySQL database is inherently versioned. Its location is an important part of the snap rollback strategy. Every time the snap updates, it creates a copy of the data directories for the update, and leaves the old data sitting alongside the old snap revision (it keeps two or three of these around by default). Then the upgrade runs its database migrations, etc., and assuming all is good, eventually in subsequent updates that old revision and its data are culled. However, in the event that the update went sideways, one can simply run `snap revert nextcloud` and be back up and running on the previous revision with the previous database. If we move the database out of this directory, that story simply can't happen.

It sounds like you're using a Raspberry Pi or something similar, is that true? You might consider setting it up such that `/var` or even just `/var/snap` is on the HDD instead of the SD, and that will accomplish your goal while not interfering with the snap's safety mechanisms.

**Comment by dniku** [comment]
Probably symlinking or bind-mounting `/var/snap/nextcloud` to an external HDD will be the simplest approach. Thank you.
