### ISSUE TITLE
replace mySQL with MariaDB

### ISSUE THREAD

**Issue by Guillaume99** [nextcloud/nextcloud-snap#147]
NC 11 is tested with MariaDB (https://nextcloud.com/news/ chapter Test setup and generalization) I think it would be great to use the same settings ...

**Comment by kyrofa** [comment]
The NC 11 [admin manual](https://docs.nextcloud.com/server/11/admin_manual/configuration_database/linux_database_configuration.html) doesn't seem to prefer one over the other: "The MySQL or MariaDB databases are the recommended database engines."

Note that I don't really have a preference, but we've been using MySQL. If we move to MariaDB now we would need to make that migration seamless for the users, which is not an insignificant effort. Does migrating to MariaDB get us anything extra, or would it be time invested for essentially nothing?

**Comment by Guillaume99** [comment]
well ...
we would have the glory of using mariadb ... :-(
My though was that the DB was totally compliant, and that we can move from one to another seamlessly, but that maybe not the case.

**Comment by oparoz** [comment]
FYI, MariaDB is not supported on ARM.

**Comment by kyrofa** [comment]
> FYI, MariaDB is not supported on ARM.

Well, there's a deal-breaker!

**Comment by oparoz** [comment]
Indeed :). On top of that, the config has to be changed for MariaDB 10.1 (not compatible with MySQL 5,7), so as you mentioned, the effort is significant.

**Comment by ottok** [comment]
@oparoz Why do you claim that MariaDB is not supported on ARM? MariaDB has wider platform support than MySQL

@kyrofa ..and why do you take a claim uncontested when there is no link or anything supporting the claim?

MariaDB ships as default in Debian and builds on all of their official and unofficial architectures, see list of built packages on official architectures at the end of the page at https://packages.debian.org/stretch/mariadb-server-10.1

Here is the same listing for Ubuntu: https://packages.ubuntu.com/artful/mariadb-server-10.1

**Comment by kyrofa** [comment]
@ottok because @oparoz is upstream Nextcloud, and we've worked together enough that he has earned my trust and respect. However, perhaps this claim is no longer true. Regardless, my real problem with this is the work involved for unknown gains. I have yet to see solid reasons why MariaDB is better than MySQL, and migrating one to the other in a seamless manner sounds non-trivial.

**Comment by kyrofa** [comment]
To be clear: I have no strong feelings about MySQL versus MariaDB. The fact of the matter is that we used MySQL from the beginning (back when this was ownCloud), because I was familiar with it. If someone can show that:

1. We can provide a seamless upgrade experience for every one of the thousands of nextcloud snap users from MySQL to MariaDB, and
2. There are enough benefits to using MariaDB to make the work for (1) worth it

Then I will of course consider it. To date, no one has done so.

**Comment by ottok** [comment]
We'll, it is true that the difference is not huge. I'd still recommend to try to at least see if it really is a lot of work. And I can help if you run into issues that are not easy to yourself.

Here are some pages argumenting for benefits:

* https://mariadb.com/products/why-mariadb
* https://mariadb.com/resources/blog/why-should-you-migrate-mysql-mariadb
* https://seravo.fi/2015/10-reasons-to-migrate-to-mariadb-if-still-using-mysql

**Comment by pachulo** [comment]
> If someone can show that:
> 1. We can provide a seamless upgrade experience for every one of the thousands of nextcloud snap users from MySQL to MariaDB, and
> 2. There are enough benefits to using MariaDB to make the work for (1) worth it
> Then I will of course consider it. To date, no one has done so. In fact, I've yet to see a single technical reason for switching.

Sorry for the necroposting, but I've just read about some performance arguments for 2 [(source)](https://lists.ubuntu.com/archives/ubuntu-devel/2024-September/043130.html) that I think are interesting to share:
* https://smalldatum.blogspot.com/2024/04/sysbench-on-small-server-mariadb-and.html
* https://smalldatum.blogspot.com/2024/04/sysbench-on-less-small-server-mariadb.html
