### ISSUE TITLE
Enable shell_exec to php

### ISSUE THREAD

**Issue by kimizumi1** [nextcloud/nextcloud-snap#1490]
Hello!

I need to run the geoblocker plugin for nextcloud. The plugin needs shell_exec to be enabled for the server.
There is few commands for making changes to PHP but there is not any for enabling shell_exec. Also the php.ini was visible for long time ago but not anymore

**Comment by kyrofa** [comment]
The php.ini has and always will be visible as `/snap/nextcloud/current/config/php/php.ini`. However, it is not writable, so it's probably not particularly useful. I'm afraid we disable `shell_exec` for security reasons, so I'm sorry, but I must say "no" to this request.

That said, it doesn't sound like Geoblocker actually does anything other than logging:

> This is a front end to geo localization services, that allows blocking (currently only logging is possible!) of login attempts from specified countries. (Early Version)

I really suggest doing this at the server level instead of using a Nextcloud app for it. I wrote [DCF](https://github.com/kyrofa/dynamic-country-firewall) in the past for exactly that purpose, you might look into doing something similar.
