### ISSUE TITLE
nextcloud.log is in the wrong place and is not rotated

### ISSUE THREAD

**Issue by Torom** [nextcloud/nextcloud-snap#1534]
#### Describe the bug
nextcloud.log is not located in /var/snap/nextcloud/current/logs/ as expected, instead it is located on the external hard drive configured as 'datadirectory' in config.php. It is also not rotated there and is now 53 MB in size.

#### To Reproduce
Steps to reproduce the behavior (not tested):
1. Set 'datadirectory' in config.php to /media/wd_ext/nextcloud
2. nextcloud.log is now in /media/wd_ext/nextcloud/
3. There is no nextcloud.log in /var/snap/nextcloud/current/logs/

#### Expected behavior
nextcloud.log should be in /var/snap/nextcloud/current/logs/ with the other logfiles

#### OS/snapd/snap version
Ubuntu 20.04 on a Raspberry Pi 4

```
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.1snap1  24060  latest/stable  nextcloud✓  -
```
```
$ snap version
snap    2.47.1+20.04
snapd   2.47.1+20.04
series  16
ubuntu  20.04
kernel  5.4.0-1022-raspi
```

#### Logs
[Logs.txt](https://github.com/nextcloud/nextcloud-snap/files/5474879/Logs.txt)

**Comment by kyrofa** [comment]
I actually did that by design, but you're making me re-think it :wink: . Tell me what you think.

I feel like the snap reasonably "owns" its components. It uses apache, for example, but the user is never meant to care-- I should be able to swap it out for nginx and no one should notice. Same for redis, or mysql. Therefore I felt okay reorganizing the logs for those components in a way that I could reliably rotate them.

However, I didn't feel that the Nextcloud log fit into the same category. It's the log of the thing users are actually directly consuming and care about: Nextcloud. Nextcloud by default puts that log in whatever directory is being used as the data directory, which the user can change. We can't support rotating a log that can move around, so we'd need to move it into that `logs/` directory. I was worried that users might be monitoring or otherwise using that log, so I opted not to make that happen on existing installs. The only way you end up with a `nextcloud.log` file in there is in _new_ installs.

What do you think-- is getting the log rotation and common log location a big enough plus that you think users won't be too upset if we move that log around?

**Comment by kyrofa** [comment]
While we're discussing this, by the way, you can tell Nextcloud to log to the proper location where it will be rotated by adding these three lines to your `config.php`:

```php
'log_type' => 'file',
'logfile' => '/var/snap/nextcloud/current/logs/nextcloud.log',
'logfilemode' => 0640,
```

**Comment by Torom** [comment]
Thanks for the answer. I think it makes sense to have all logfiles in one place and to proceed with them in the same way. It is rather unintuitive to search the Nextcloud logfiles at a different location than all other logfiles. Also, it is a one-time change, so users should be able to handle that.

In my case I will remove the logfiles from the external hard disk, I hope that the hard disk will not have to wake up with every cron call, or does it have to do that anyway for cron?

**Comment by Torom** [comment]
I've tested it for a few days now and the hard disk doesn't seem to start up unnecessarily anymore. This is another reason for me not to have nextcloud.log in 'datadictory', since it is mostly used for external drives.

**Comment by Torom** [comment]
Since it does not seem to be a real bug and my problem has been fixed, I close the issue. I think nextcloud.log should be placed with the other logfiles, but I understand why moving the logfile is not done automatically. Since new installations behave correctly this should be done by itself at some point.
