### ISSUE TITLE
How to change channel to stable from Edge

### ISSUE THREAD

**Issue by merrpink** [nextcloud/nextcloud-snap#1555]
#### Describe the bug
In version 20.0.1 stable, sharing doesn't work so I changed my channel to Edge. Now sharing works but Talk doesn't work. It is disabled by default and every time I hit the "enable" button in the web page nothing happens. So I tried to revert back to the stable version and was informed that Nextcloud does not support downgrades. So I did a revert, which brought me to the version from one day ago. Tried revert again, hoping to reach stable step by step, and was informed that there  was "no revision to revert to." 

So how to get back on the stable channel from edge is my first question, and second, will Talk be back online soon. It didn't work in previous edge nor does it work in the present edge. Everything else seems to be fine.

Thanks

#### To Reproduce
1. Look at top bar and see no talk
2. Goto Apps and find Talk disabled
3. Click enable and see nothing happen.

#### Expected behavior
Talk icon would be visible in top bar and Talk would work by default.

#### OS/snapd/snap version
Ubuntu 20.04

    $ snap list nextcloud
Name       Version            Rev    Tracking     Publisher   Notes
nextcloud  master-2020-11-29  24680  latest/edge  nextcloud✓  -
reverted to this version today trying to get back to stable.

and:

    $ snap version
snap    2.47.1+20.04
snapd   2.47.1+20.04
series  16
ubuntu  20.04
kernel  5.4.0-53-generic

If you need more information, please tell me specifically. Your script is very broad. Thanks.

**Comment by kyrofa** [comment]
Yeah this is a sticky situation, because Nextcloud doesn't support downgrades. Reverting was the way to go, but by default snapd only keeps a few snaps around for reverting. If you continue to run on edge you update every day and you quickly lose your ability to revert. I don't recommend running long-term on anything other than the */stable channels.

The best bet for you (barring a re-install) would be to try refreshing to `20/edge`. At least then you aren't tracking the Nextcloud master branch, where stuff is broken all the time. That might be SOMEwhat more stable. Then you can wait for another v20 release to come out where you might be able to get back to stable. The refresh to `20/edge` is iffy though, it's entirely possible that master has introduced changes such that this refresh would also be considered a downgrade. Keep an eye on your logs.

If all else fails, you'll need to back up your data and reinstall a more stable version. Please also ensure you're logging bugs upstream so your current issues in edge are resolved.

**Comment by merrpink** [comment]
@kyrofa Ok thanks
