### ISSUE TITLE
proxy.php of richdocumentscode tries to run pidof

### ISSUE THREAD

**Issue by timar** [nextcloud/nextcloud-snap#1572]
#### Describe the bug
The built-in Collabora Online server app (richdocumentscode) tries to run `pidof` command, in order to check it the service is already running.

In `/var/snap/nextcloud/24828/log/php-fpm_errors.log` the log indicated that `pidof` command is not allowed to run in the snap.

`[08-Dec-2020 22:08:46] WARNING: [pool www] child 20232 said into stderr: "sh: 1: pidof: Permission denied"`

Can you please allow it?

**Comment by kyrofa** [comment]
I'm afraid no snap interfaces cover `pidof`, so no, that's not something we have the ability to allow here. If it helps, the way most daemons work (e.g. php, apache) is they write their pid to a file and then operations can run using that file. You might consider doing something similar rather than using a tool like `pidof`.
