### ISSUE TITLE
I keep on getting these issues in my nextcloud about out of date mySQL and no imagick

### ISSUE THREAD

**Issue by MadMacMig** [nextcloud/nextcloud-snap#1644]
I keep on getting these issues in my nextcloud about out of date mySQL and no imagick even though I have installed imagick. But I am not too sure about the mySQL

![nextcloud error Capture](https://user-images.githubusercontent.com/61500100/107544616-53e0c900-6bc2-11eb-9e54-5a5b4f659ae3.PNG)

**Comment by kyrofa** [comment]
@MadMacMig please see #1626 for mysql, you don't need to do anything. Regarding imagick, you're seeing that warning because the theming app wants to use it for favicon generation, and the snap doesn't include it as it's a security concern.

@kesselb I've got a non-stop stream of issues and pings about this mysql message. Would you mind passing along my frustration to whoever decided that was a good idea? Surely there has to be a better way to notify maintainers about this, or allow maintainers to selectively hide things like this.

**Comment by kesselb** [comment]
> Would you mind passing along my frustration to whoever decided that was a good idea?

Will do.

> I've got a non-stop stream of issues and pings about this mysql message

I'm using a pinned FAQ issue on nextcloud/server for a while. That seems to help a bit to redirect people to the right issues.

**Comment by kyrofa** [comment]
Good call on the pinned issue, I'll give that a try.
