### ISSUE TITLE
Support for Ubuntu Core 20?

### ISSUE THREAD

**Issue by jans23** [nextcloud/nextcloud-snap#1646]
Hi!
Do you plan to support Ubuntu Core 20 in the near future?

**Comment by kyrofa** [comment]
There are two ways for me to interpret that question, so I'll answer them both.

1. Can I install the Nextcloud snap on Ubuntu Core 20?

Absolutely, this is due to the beauty of snaps. Every snap declares a `base` that indicates the execution environment it needs in order to run properly. The snap currently uses `core18` as that base, which could be misconstrued as "this snap only works on Ubuntu Core 18" which isn't true at all. It just means that it needs the core18 base snap to be installed in order to run, which is something snapd takes care of. You can install it all the way back on Ubuntu 14.04 and it will also install the core18 snap, and run perfectly. You could install it on Ubuntu Core 16 and it will install the core18 snap as well, and run perfectly. You can install it on Ubuntu Core 20 as well, and it will run perfectly because snapd will also make sure the core18 snap is there. That doesn't turn your device into Ubuntu Core 18, it just means that snaps truly are designed to run everywhere.

2. You're currently using core18 as the base. When do you anticipate switching to core20?

When there's a good reason. core18 will be supported for a long time, and it works well, and I have no desire to go hunting for problems. Snaps automatically update, and we take that responsibility tremendously seriously. Every change we make has the potential for breakage, and so we try to keep those to a minimum. This requires weighing the risks and rewards of every change. There's no risk of staying with core18, and I don't know of a reward of switching to core20. I re-evaluate every so often.

I believe this answers the question, so I'll close it, but please do feel free to continue the discussion here.
