### ISSUE TITLE
Permission errors cant create files or folders 

### ISSUE THREAD

**Issue by sign-out** [nextcloud/nextcloud-snap#175]
The only error given is that it could not create the file/folder.

This happened after I moved the data dir to /home/Nextdata not sure what else to include i think it could be that php or what ever does Nextcloud file writes has some  limited files access I don't know about that i need to change  so it works 

I used this set of instructions  https://github.com/nextcloud/nextcloud-snap/issues/150 substituting where the data dir went

**Comment by kyrofa** [comment]
Yeah you probably can't do much of anything at all, as the snap doesn't have permission to read or write to `/home/Nextdata`. The data should either be in the default location (`/var/snap/nextcloud/common`) or somewhere in `/media/` if you have the `removable-media` plug connected.

**Comment by sign-out** [comment]
is there a way i can give it permission as i need it to not be on the system drive since its tiny and the only other partition is /home

**Comment by sign-out** [comment]
@kyrofa  also i don't appear to be able to "re open" the ticket so i hope this tag works as a subsitute

**Comment by kyrofa** [comment]
There are two possibilities:

1. Install it in devmode (it'll run completely unconfined, not recommended)
2. Bind-mount a directory in /media from the larger partition and use that.

Do either of those solutions work for you?

**Comment by sign-out** [comment]
how do i bind mount a directory in to /media ? it sounds like it should work

**Comment by sign-out** [comment]
thank you for the help i figured out how to do the bind mount ^^

**Comment by Seferi** [comment]
Hi, I created a local folder named nextcloud data and also a folder in /media/nextcloud-data and bind-mounted to /media with: sudo mount --bind /home/john/nextcloud-data/ /media/nextcloud-data
and in browser i added the /media/nextcloud to external storage and got the green light. but when i go in to the directory it says 'you don't have permission to create or upload files here' What am i doing wrong?

**Comment by leventerevesz** [comment]
> When i go in to the directory it says 'you don't have permission to create or upload files here' What am i doing wrong?

Did you manage to fix this somehow?

**Comment by kyrofa** [comment]
Make sure Nextcloud's data dir is owned by root:root.

**Comment by leventerevesz** [comment]
Both Nexcloud's datadir `/var/snap/nextcloud/common/nextcloud/data` and the external dir `/home/levente/ncexternal` were owned by root:root with 770 permissions, but the UI still displayed the 'you don't have permission to create or upload files here' notification.

I gave up on that and moved the datadirectory to `/home/levente/nextcloud/data` (bind mounted to `/media/nextcloud/data`) according to the [wiki instructions](https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition) since I have more space on my /home partition. After this the external storages magically started to work, no more permission problems.

After all I have decided to just bind mount my storage folders into the datadirectory with this fstab entry

    /home/levente/foo  /home/levente/nextcloud/data/levente/files/foo  none  bind

The foo folder has to be owned by root but the group can be anything.
