### ISSUE TITLE
Installed nextcloud via snap how to set OPcache values

### ISSUE THREAD

**Issue by Dmit84** [nextcloud/nextcloud-snap#2235]
Installed nextcloud via snap. An error pops up:
The OPcache module of the PHP subsystem is configured incorrectly. Additional information is provided in the documentation ↗.
The OPcache interned string buffer is nearly full. To ensure efficient caching of duplicate strings, it is recommended to set opcache.interned_strings_buffer in the PHP configuration to a value greater than 8.

The /snap/nextcloud/current/config/php/php.ini file cannot be edited. The opcache.interned_strings_buffer=8 parameter is commented out in it. How to install it?

**Comment by ShapeShifter499** [comment]
I'm curious, what are some of the consequences of having a suboptimal OPcache setting?

**Comment by YoannPa** [comment]
Hi @kyrofa , since both issues about OPcache have been closed, I assume you found a way to let user to custom their own parameters.
Will it be available in the next snap nextcloud update ?
How will we be able to edit opcache parameters ?

Thank you in advance for your answer, and thank you for taking care of this !
