### ISSUE TITLE
reliable way of finding the Box on the local network

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/nextcloud-snap#237]
Right now, we use mdns to advertise the Box on the local network. This usually but not always work. Are there other viable solutions to find the Box?

**Comment by kyrofa** [comment]
The only situation in which I expect it not to work is on a Windows system without Bonjour. Are there other situations in which is doesn't work as well?

**Comment by diderikvw** [comment]
Yes, the mDNS/Zeroconf solution does not work in many unclear sitations having to do with unreliable ISP modem/routers, where you get whatever cheapest one the ISP could buy. We ran into this problem several years ago when we were developing a home automation solution/device. 

After spending a lot of effort identifying the problem, we came to the conclusion we needed a different solution for users to easily access the web interface, without relying on mDNS/Zeroconf.

We eventually made 2 solutions, one I will call the JavaScript scanner (JS-scanner) and one I will call internal/external IP mapping (IP-mapping):

1. JS-scanner: we made a script that scanned the local network for our device, I think a simple HTTP call on port 80 and waited for our familiair HTTP header. We pre-programmed several much used local IP ranges like 192.168.0.1, 192.168.1.1 and 10.0.0.1, as well as some ranges used on popular ISP modem/routers. This turned out to be rather user-friendly and worked reasably robust/reliable and can be made to work in a distributed situation like NextCloud Box.

2. IP-mapping: we made the device send its local IP address to a central server. Then the user could go to the public website and click a button to open the local web interface. This works because on the public server we could catch the public IP address of the device/user and then store that mapping and use it when the user clicked the button. This turned out to be our final solution, very user-friendly and very robust/reliable, but it required some more work and may not be the ideal solution in a distributed situation like NC Box, because it requires a central server.

Ad 1. I do not recall exactly anymore, but maybe we added the JS to our app, instead of on a public website to prevent cross domain scripting problems.

Ad 2. If storing a central table mapping of local and external IP addresses is seen as a too high security risk (as possible starting point for hackers for scanning ports on the external addresses, if that table would be stolen), then a variation would be to work with salted/hashed serial numbers for example.

**Comment by kyrofa** [comment]
Perhaps we should investigate using UPnP.

**Comment by oparoz** [comment]
> The only situation in which I expect it not to work is on a Windows system without Bonjour. Are there other situations in which is doesn't work as well?

Never worked for me, even with several Bonjour services running.

@diderikvw Thank you very much for this valuable input :)
I think option 1 would be best in our case as I don't think our users would appreciate if their device was phoning home.

I did suggest a while back that we should have a simple desktop app which can scan the network. That's what a lot of storage and networking equipment vendors do. Should be fairly simple to develop using something like QT.

**Comment by kyrofa** [comment]
Closing as it's no longer relevant. Might be time to consider removing the mdns feature altogether these days.
