### ISSUE TITLE
Can't run nextcloud.enable-https with sudo

### ISSUE THREAD

**Issue by kristbaum** [nextcloud/nextcloud-snap#31]
nextcloud.enable-https does require root, but can't be executed with sudo. The error is "sudo: nextcloud.enable-https: command not found". 
It works if you emulate a root shell with sudo -i. Is this maybe an issue with snap-confinement?

**Comment by oparoz** [comment]
You need to call a different binary:
`sudo /snap/bin/nextcloud.enable-https`

**Comment by kyrofa** [comment]
Yeah, `/snap/bin/` isn't in the path for sudo at the moment (a bug which been fixed but is being SRUd, which takes a bit). A workaround while we're waiting is to use the absolute path as @oparoz mentioned.

**Comment by kristbaum** [comment]
So it the bug is in snapd?

**Comment by kyrofa** [comment]
> So it the bug is in snapd?

It ended up being fixed in sudo (LP: [#1595558](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1595558)).

**Comment by kristbaum** [comment]
Ah thanks, is it okay if I leave the issue open until the fix comes out of xenial-proposed?

**Comment by kyrofa** [comment]
Oh certainly, I probably would have re-opened it if you closed it :smile: .

**Comment by kristbaum** [comment]
Great, so let's: Ceep Calm, and sudo apt update! ;)

**Comment by kyrofa** [comment]
Just saw that this works in 16.04 now. Make sure you're up-to-date.

**Comment by alexpattyn** [comment]
This issue seems to still exist on Fedora 31 Server. After following https://snapcraft.io/docs/installing-snap-on-fedora I can install nextcloud but running...

```
[apattyn@localhost ~]$ nextcloud.enable-https lets-encrypt
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
chmod: changing permissions of '/tmp/pids': Operation not permitted
This utility needs to run as root
[apattyn@localhost ~]$ sudo nextcloud.enable-https lets-encrypt
sudo: nextcloud.enable-https: command not found
```

Wasn't sure if cgroups v2 was causing an issue but running the same command above but with `/snap/bin/nextcloud.enable-https` instead works.

**Comment by roadev** [comment]
> This issue seems to still exist on Fedora 31 Server. After following https://snapcraft.io/docs/installing-snap-on-fedora I can install nextcloud but running...
> 
> ```
> [apattyn@localhost ~]$ nextcloud.enable-https lets-encrypt
> WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
> chmod: changing permissions of '/tmp/pids': Operation not permitted
> This utility needs to run as root
> [apattyn@localhost ~]$ sudo nextcloud.enable-https lets-encrypt
> sudo: nextcloud.enable-https: command not found
> ```
> 
> Wasn't sure if cgroups v2 was causing an issue but running the same command above but with `/snap/bin/nextcloud.enable-https` instead works.

Same issue here on debian!

**Comment by kyrofa** [comment]
Yeah you might need to reboot to get `/snap/bin` onto your PATH, or you might need to add it yourself. In reality though, the snap cross-platform story is a bit of a stretch, I really don't recommend snaps unless you're on Ubuntu. Otherwise you'll (in most cases) end up running daemons as unconfined root, which is a terrible security practice.
