### ISSUE TITLE
Snap limitations

### ISSUE THREAD

**Issue by Sankia** [nextcloud/nextcloud-snap#383]
Hi there,

I'm somewhat new to his, we're looking to deploy nextcloud as a resellable resource for cloud data as an add-on for our customers, this will require the installation of a 3rd party app (Hostbill/Nextcloud API) am I correct in assuming this cannot be done using the snap install because the snap cannot be modified (so we can't paste the app to the correct folder?)

Also, any idea how to change the favicon in the snap, I tried modifying the favicon.ico but the location is read-only so I can't replace anything.

**Comment by kyrofa** [comment]
Hey @Sankia, thanks for opening an issue.

> [...] this will require the installation of a 3rd party app (Hostbill/Nextcloud API) am I correct in assuming this cannot be done using the snap install because the snap cannot be modified (so we can't paste the app to the correct folder?)

Oh heavens no, Nextcloud's usefulness would be tremendously limited without being able to install any apps! You're right, the snap itself is read-only, which means the included apps directory is also read-only. However, Nextcloud supports multiple app directories, and the snap uses this to great effect by having a second apps directory that is writable. When you install an app, it goes into that directory. It's located in `/var/snap/nextcloud/current/nextcloud/extra-apps`.

> Also, any idea how to change the favicon in the snap, I tried modifying the favicon.ico but the location is read-only so I can't replace anything.

This I've never done before. I figure it'd be part of Nextcloud's theming capabilities, although I'm afraid this is also something I've not done. Have you experimented with the [theming app](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/theming.html)? I can say that, if you need to replace web assets with your own, you're right, that will not be possible in the snap due to its read-only nature. But I suspect the theming app will offer the functionality for which you seek.

**Comment by DroWnThePoor** [comment]
@kyrofa I'm using the nextcloud snap on my raspberry pi via ubuntu-core, I wish to install https://github.com/pbek/qownnotesapi what would be the best way to go about doing this?

**Comment by kyrofa** [comment]
@DroWnThePoor I've never used it, but it sounds like you should just be able to clone it to the directory I mentioned above and enable it, like it says in its README.

Not sure why it's not in the store, though.

**Comment by DroWnThePoor** [comment]
Should everything in Extra-Apps have root ownership? The directory itself is owned by root, so I would assume yes.

And getting the repo into the OS is also a concern, Ubuntu-Core is centered around installing everything via Snaps, butt I'll have to look around some more, I couldn't find a Git Snap.

**Comment by kyrofa** [comment]
Yes, everything should be owned by root there.

And yeah, you'll need a [dev setup](https://developer.ubuntu.com/core/get-started/developer-setup) to install things like git etc. It's basically another special snap.

**Comment by DroWnThePoor** [comment]
@kyrofa Thank you so much, greatly appreciated.

**Comment by kyrofa** [comment]
Sure thing. I'll go ahead and close this, now.
