### ISSUE TITLE
Debian Stretch error

### ISSUE THREAD

**Issue by selfus** [nextcloud/nextcloud-snap#391]
Installed snapd on a RaspberryPi running Raspbian based on Stretch.

Tried to install next cloud with sudo snap install nextcloud

Got this error:

INFO snap "core" has bad plugs or slots: core-support-plug (unknown interface)
error: cannot communicate with server: Get http://localhost/v2/changes/1: dial unix /run/snapd.socket: connect: connection refused

**Comment by kyrofa** [comment]
I'm afraid I'm unsure what's happening there. It's possible that the snapd you have available is out-of-date. Please open a topic in the [snapd category of the Snapcraft forum](https://forum.snapcraft.io/c/snapd) and ask. The people there will know what's happening.

I'll go ahead and close this since it's not a Nextcloud snap issue, but feel free to continue discussions here if desired.
