### ISSUE TITLE
Update to Nextcloud 10

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/nextcloud-snap#40]

**Comment by kyrofa** [comment]
Waiting on nextcloud/server#1081 to make it into a release.

**Comment by MariusBluem** [comment]
10.0.1 Is out 🎆 ... Lets Update 💪 @kyrofa

**Comment by kyrofa** [comment]
@MariusBluem woohoo! Thanks for the update :smile: .

**Comment by fishscene** [comment]
What is the status of this? A few days ago, the 10.0.1snap1 milestone had 4 issues in it. Now it has
12 - are these delaying the 10.0.1snap1 update?

**Comment by oparoz** [comment]
* 4 of these are PRs which match an issue
* Some are long overdue bugs which should be easily resolved
* Some can be moved to snap2 if necessary, they won't block the release

The only ones which could delay the release are security related, the rest can even be merged on 9 as they are since they've been tested on 9.
