### ISSUE TITLE
Wish to change nginx.conf to set proxy by path

### ISSUE THREAD

**Issue by Meepoai** [nextcloud/nextcloud-snap#445]
Hello, Autor!  I am a user form china, for some reasons, I want to change the nginx.conf in nextcloud which was installed by snap. Because I want to set some proxy by path like this
` 
 location /myproxy {
    proxy_redirect off;
    proxy_pass http://127.0.0.1:11111;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;

  }
`
and I see some other issues about it, but I have to set proxy by path instead of using another port,
Thanks for any replies.
(forgive my poor english..

**Comment by kyrofa** [comment]
Hey there! Welcome, and thank you for logging an issue.

Note that the snap uses apache, not nginx. That said, you can't modify its config either (by design). If you want to setup a reverse proxy, you can change the port of the snap (or put it on another network one way or another) and proxy to it. See [this wiki page](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy) for some more details.
