### ISSUE TITLE
redirect http to HTTPS on SNAP

### ISSUE THREAD

**Issue by paschalis-ch** [nextcloud/nextcloud-snap#464]
Hello

I have installed the nextcloud 13 snap and now I would like to configer the server so that http will redirect permanently to https. I know, there are a lot of manuals in nextcloud communities but with a snap install, I don't know where I have to do the configuration.
Thanks for your support

**Comment by r4co0n** [comment]
Did you see this wiki entry about enabling https? There is also [this part](https://github.com/nextcloud/nextcloud-snap#httphttps-port-configuration) about http and https port configuration in the README if you want custom ports.
All you should need to do is run
```
sudo snap run nextcloud.enable-https [letsencrypt | self-signed]
```
using letsencrypt if you have a public domain name pointing to your Nextcloud instance (NC reachable via e.g. http(s)://yourdomain.example.com ) and self-signed otherwise (NC reachable in private network via e.g. http(s)://192.168.0.5 ). This will enable TLS with HSTS and make HTTP requests being redirected to HTTPS, unless I am mistaken. I am somehow confused because from what you write it seems that HTTPS is working, but HTTP is not redirecting. However, the default behaviour (I just re-tested) for this snap is to redirect HTTP to HTTPS on running the above command.

**Comment by paschalis-ch** [comment]
Hi and thanks for your respons

I don't know if HTTPS is enabled but if I want to connect via https://192.168.x.x the connection doesn't works.

When I would run the command you said, I gett this message
No such subcommand: [letsencrypt. Run 'nextcloud.enable-https -h' for help.
self-signed]: Command not found.

Thank you

**Comment by r4co0n** [comment]
Sorry for the confusion, you need to run:
```
sudo snap run nextcloud.enable-https self-signed
```
Or replace `self-signed` with `letsencrypt` under the conditions described above. Having nothing listening on HTTPS by default is expected as the server has no ssl certificate, this is provided, obtained and/or generated in the `enable-ssl` subcommand.

See
```
sudo snap run nextcloud.enable-https -h
```

**Comment by paschalis-ch** [comment]
Hi 

Thank you very much, it works !!

**Comment by r4co0n** [comment]
You should be able to close this issue, as you are the owner, if your problem is solved. It should be available as a separate button below the comment box. This helps because otherwise we have to wait a project admin to find, read and close this.

**Comment by kyrofa** [comment]
Note that to get a Let's Encrypt cert, you need to `lets-encrypt` as the subcommand (note the hyphen).

**Comment by kyrofa** [comment]
Thanks for being all over this @r4co0n, very helpful :) .

**Comment by nickosouras** [comment]
the link to the solution no longer works. anyone know what it was or have an idea why it doesnt work?

**Comment by herrxyz** [comment]
just installed nextcloud using snap on debian 10 and "sudo snap run nextcloud.enable-https self-signed" worked perfectly

**Comment by tommasobenatti** [comment]
Hi, there is a way to replace the self-signed with the lets-encrypt one?

**Comment by kyrofa** [comment]
Try running `sudo nextcloud.disable-https` and then `sudo nextcloud.enable-https lets-encrypt`.
