### ISSUE TITLE
Display in contacts wrong

### ISSUE THREAD

**Issue by rabadumpf** [nextcloud/nextcloud-snap#467]
Hello!
When I call the contacts app, my contacts appear as splashes of color. What is wrong? What must I change (see attachment).
![bildschirmfoto vom 2018-03-04 09-19-09](https://user-images.githubusercontent.com/26359952/36943697-8f8d72ca-1f8d-11e8-86d4-f63834df9dc1.png)

**Comment by r4co0n** [comment]
I had the same problem. I followed what @kyrofa described [here](https://github.com/nextcloud/nextcloud-snap/pull/442#issuecomment-364594397).
Adapted a little:
```
sudo rm -r /var/snap/nextcloud/common/nextcloud/data/appdata_*/{css,js}/*
sudo snap run nextcloud.occ files:scan-app-data
```
Afterwards, reload the page without using cached data (Should be [Ctrl]+[F5]). That fixed things for me.

**Comment by kyrofa** [comment]
Thanks @r4co0n!

@radhus it would help if you said which version of the snap you were using, but if you're using `13/candidate` @r4co0n is on the money. You could also consider using `13/edge` which has the fix for that bug.

**Comment by radhus** [comment]
Ping @rabadumpf 😉

**Comment by r4co0n** [comment]
That's interesting... This happened on `12.0.5snap1 (5132)` for me on the `stable` channel. I had read @kyrofa's message linked above earlier and what I saw (It was almost exactly like in the screenshot) made me want to clear my browser cache and rebuild assets, so I did what I described in my first post and my problem was gone. This happened after updating contacts to `2.1.1`.

Now `2.1.2` is out and the formatting is wrong again. This time, contacts without an email have a contact bubble that's vertically misaligned.

![nc_contacts_bubbles_misaligned](https://user-images.githubusercontent.com/6705437/37020758-4156441a-211d-11e8-9329-59574d0a7da0.png)

This however, cannot be fixed in the same way and persists after recollecting app data and purging the browser cache. Maybe this should get forwarded to the contacts repo? Looking at the bugs, I couldn't find anything really matching what we see here.

**Comment by rabadumpf** [comment]
@r4co0n : 
```
sudo rm -r /var/snap/nextcloud/common/nextcloud/data/appdata_*/{css,js}/*
sudo snap run nextcloud.occ files:scan-app-data
```
this help for me, thanks

Everything is fine after the update to 2.1.2
What do you mean wrong with  contact bubble that's vertically misaligned?
With me the data, which have no mail address, displayed correctly. Behind the phone number is a speech bubble. No idea if you mean that?

**Comment by r4co0n** [comment]
I mean the circles with the letter in front of the contact name, where a photo would appear. This is misaligned for contacts without an e-mail address (which is shown in a second line below the name). The circles float too high, as you can see in my screenshot. First and third contact are broken, second is fine (has two lines).

**Comment by rabadumpf** [comment]
@r4co0n : I have the same behavior with my contacts

**Comment by kyrofa** [comment]
This is an old bug. If it's still valid, please log it against [upstream Nextcloud](https://github.com/nextcloud/server).
