### ISSUE TITLE
sync without client and permissions

### ISSUE THREAD

**Issue by elcolumbio** [nextcloud/nextcloud-snap#508]
sync without client and permissions
i show my actual workaround to this problem.
i put this into: sudo crontab -e

*/3 * * * * /bin/chown -R root:sudo /mynextclouddatafolder/
*/3 * * * * /bin/chmod -R 0771 /mynextclouddatafolder/
*/3 * * * * sudo nextcloud.occ files:scan --all background:cron

i change permissions because scripts which aren't run by root are adding files directly to the server.
But the scripts are run by a member of the sudo group, so i set this group and give it all permissions.
Is my workaround fine? It feels very wrong.
Or should we add something like this to the built in cron?

**Comment by r4co0n** [comment]
The snap should (must?) not change permissions on files outside of its confinement area. And I agree that what you're doing feels wrong.
Some ideas to move along, after the '->' i put some keywords that might help you solve this:
1) Why aren't your scripts setting the correct permissions when they're running? -> setgid directories
2) You are doing every command concurrently (iinm)? I don't think it's the best idea to change ownership and permissions on files while they are being indexed by nextcloud. You might want to call a single script containing all the commands via cron.
3) What happens if your import takes longer than 3 minutes? -> lockfile

**Comment by elcolumbio** [comment]
ok thank you. You are right my script should make the correct files in the first place.
