### ISSUE TITLE
Make .htaccess read-write

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#52]
That file needs to be modified via occ to enable some features such as shorter URLs.

**Comment by kyrofa** [comment]
This may be problematic:

- Does `occ` have a hard-coded path where it thinks it'll find .htaccess? Because the one in the snap is read-only.
- Since the .htaccess file is read-only, we just include it in the Apache config instead of actually enabling AllowOverride. That will need to change as it will turn into a security issue, which will cause a performance hit.

**Comment by oparoz** [comment]
OK, so the alternative is probably to make the modifications ourselves if that works a 100% of the time.
All it does is add a mod_rewrite rule and we control the env, so it shouldn't be a problem.

Should I open another issue which only covers shorter URLs?

**Comment by oparoz** [comment]
Pretty URLs are discussed here: https://github.com/nextcloud/nextcloud-snap/issues/86
