### ISSUE TITLE
Script for checking if nextcloud has crashed, and if it has, restart it.

### ISSUE THREAD

**Issue by fredrikburmester** [nextcloud/nextcloud-snap#523]
I do not have a lot of RAM dedicated for my NextCloud server and it has crashed a few times (and yes I have a properly setup swap file). I would like a script that checks the state of the NextCloud service and if it's having trouble, restart it. 

Is there any finished script out there or could someone help me out? I do not really know how to write a script and would appreciate some help. 

What language does one use to write scripts? I would also like to learn to write my own scripts. 

Thank you in advance!

**Comment by fredrikburmester** [comment]
Hi! Thanks for the response. I also have 1GB of dedicated RAM on my VM running Ubuntu Server with NextCloud. This is the issue I faced and why I wanted to write a script. [https://github.com/nextcloud/nextcloud-snap/issues/518]. Thank you for the scrips tip, do you have any more suggestions?

**Comment by JamesBream** [comment]
That's odd, I suppose NC must be pretty hungry with larger files. I've only been dealing with relatively small files on my instance so that might be why I haven't run into any issues.

I see in the other thread you mentioned that you had 1GB of swap configured. Could you try running `watch free -h` in your terminal, which will show you your memory usage metrics, then try moving/deleting some large files to try produce a crash. You should see here if your system is running out of swap space, in which case you might want to try increasing it to 2GB. 

Ideally you'd increase available RAM but if you're swapping to an SSD and this isn't a common occurrence, increasing your available swap might stop things from grinding to a halt - albeit don't expect stellar performance.

Some further thoughts on the script, I'd do something like the following:

    #! /usr/bin/sh

    function check {
        if [ $? -ne 0 ] ; then
            snap restart nextcloud
            exit 1
        fi
    }
    curl -s -o "/dev/null" http://mynextcloud.com
    check;

Just FYI, I've no idea if the above will work as I'm not exactly well versed in shell scripting nor have I tested it so it might need tweaking. Simply, it uses curl to try get your NC homepage and then checks whether a success was reported ($? = 0) or if not, you probably need to do your restart. In theory, that should work. Save it as a `.sh` script somewhere then set crontab up to run it as frequently as you'd like.

**Comment by fredrikburmester** [comment]
Thank you! I will try to implement the script and let you know. I tried what you said and ran `watch free -h` and moved a file. I moved the file with a size of **4.4GB** from an external drive to the internal /data/ folder. The RAM usage went up to **907MB** and the swap increased to **312MB**. While the server was moving the file I reloaded the page and got this error message from the server:
https://imgur.com/a/L8eMBnq

**Comment by kyrofa** [comment]
I believe this question has been answered, so I'm going to close it. Feel free to continue discussions here.
