### ISSUE TITLE
Update TLS ciphers list

### ISSUE THREAD

**Issue by bn4t** [nextcloud/nextcloud-snap#538]
I think it would be reasonable to update the TLS ciphers list according to the "modern" configuration of https://mozilla.github.io/server-side-tls/ssl-config-generator/

I'd be more than happy if some people share their thoughts on this topic since this would break compability to some older browsers.

**Comment by kyrofa** [comment]
Thanks @bn4t, I appreciate your looking into this. However, I find there are approximately an _infinite_ number of recommendations out there for this stuff. What the snap uses now gets an A+ on [SSL Labs](https://www.ssllabs.com/ssltest/). I suggest we leave the suite alone unless that score drops, or until someone provides an otherwise compelling reason to change them.
