### ISSUE TITLE
Inotify file watcher can't be enabled

### ISSUE THREAD

**Issue by 3v1n0** [nextcloud/nextcloud-snap#547]
Installing the [app](https://apps.nextcloud.com/apps/files_inotify) fails with this error:

`App "INotify file watcher" cannot be installed because the following dependencies are not fulfilled: The library inotify is not available.`

I wasn't able to find any other (more relevant) log.

**Comment by kyrofa** [comment]
Hey @3v1n0, we try to ensure all the default apps are capable of running in the snap, but I'm afraid ensuring all dependencies for all apps are present doesn't scale, and this request falls into that category. I'm afraid if you need this app you'll need to install Nextcloud in another way, run a file scan manually, or move files using webdav instead of mounting underneath Nextcloud.

**Comment by 3v1n0** [comment]
Right now I'm just using a script for triggering something similar using `inotify-watcher` but is adding such so basic lib support causing many changes?

**Comment by 3v1n0** [comment]
Hey, wondering if this is something we can include :)

I mean, your point is correct, but monitoring file changes looks to be quite a needed scenario for a cloud system, so.... 

Meanwhile I'm stuck with a systemd launched script that basically uses [inotifyexec](https://github.com/bkanuka/inotifyexec/) to run  `sudo nextcloud.occ files:scan -n --path=$foo`

**Comment by mailinglists35** [comment]
https://snapcraft.io/docs/removable-media-interface mentions this:

>removable-media is considered a transitional interface because, when connected, only traditional UNIX permissions are considered for file access. **This allows a background service in a snap to setup inotify**, for example, to monitor, catalogue and modify files on external media.

Would it be possible to revisit this feature and check if the snap version of nextcloud can make use of that feature?
