### ISSUE TITLE
Why are all the daemons launched in the foreground?

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#56]
Daemons like PHP-FPM are usually launched in the background and spawn children.
What is the reason for all our daemons to be launched in the foreground?

**Comment by kyrofa** [comment]
An important distinction: they aren't necessarily launched in the background, they're run in the foreground but they typically fork and exit. snapd supports different service types, two of which are "simple" and "forking," the meanings of which are the same as systemd.

A few of the services we run are indeed typically forking services, but we run them as simple services because back when the snap was initially created snapd has some bugs around its forking implementation. Since it's working fine at this point I saw no upside in investing time to use forking, even though I assume those bugs have been ironed out.

**Comment by oparoz** [comment]
True, foreground and fork.
I know it works fine with PHP-FPM, but let's wait for the final release before revisiting. Thanks!
