### ISSUE TITLE
Which email server is recommended to use with nextcloud-snap?

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/nextcloud-snap#588]
Which email server is recommended to use with nextcloud-snap?

The inclusion of users tools to include internal mail messaging and external www email is really vital and a enhancement on any file sharing application. Which email server is the one most popular and widely used for nextcloud-snap installed websites?

Someone has obviously tested quite a few email servers with their nextcloud-snap install to discern which of those tested, served this purpose in a reliable, effective manner and which did not.

**Comment by kyrofa** [comment]
That's impossible to answer in an unbiased manner, and is not at all specific to the snap. You can use gmail, or your domain service provider, or any number of other options. You should open a [forum topic](https://help.nextcloud.com/) to get thoughts from the community at large instead of limiting yourself to snap users.
