### ISSUE TITLE
It is wise to add files directly to /var/snap/nextcloud/common/nextcloud/data/USER/files/Nextcloud.mp4

### ISSUE THREAD

**Issue by IvanTurgenev** [nextcloud/nextcloud-snap#603]
I have some files on my server and i want to add them to nextcloud which is installed on the same server, is this a good way to just add those files directly?

I found that by searching the file system

**Comment by r4co0n** [comment]
You have found the right folder, if you are not using encryption, you should be able to put the files in a subfolder there, giving them similar permissions as existing files (here they are `root:root 644`). Then by running `snap run nextcloud.occ files:scan --path <user-id>/files/<my-subfolder>` the files will be indexed and become visible for the respective user.

[This forum post](https://help.nextcloud.com/t/adding-files-to-nextcloud-without-uploading/2847) goes a little deeper into this, also linking to the [documentation](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/occ_command.html#file-operations)(here the apparently unchanged doc for version 13) of the `files` command. 

You can also use Nextcloud's external storage with the `Local` backend, that's what I would recommend.

To do that:
1. Make sure the files are accessible by the nextcloud snap. For that, they have to reside somewhere under `/media/`:
   (Do either)
  1a. If the files are on a separate mountpoint, change that to point to e.g. `/media/nextcloud-extrafiles`.
  1b. Otherwise, you can use a bind-mount to replicate an existing directory tree somewhere else, e.g. mirror `/var/www/catpics` to `/media/nextcloud-catpics`.
2. Take note of the folder you used in `/media`.
3. Allow the nextcloud snap to access `/media`: `snap connect nextcloud:removable-media`
4. [Configure](https://docs.nextcloud.com/server/13/admin_manual/configuration_files/external_storage_configuration_gui.html) `Local` external storage using the folder from 2. .

**Comment by IvanTurgenev** [comment]
Wow thanks for the answer but endedup using seafile since nextcloud snap installation uses an absurd amount of memory  #513
