### ISSUE TITLE
Path to occ for cron job [help]

### ISSUE THREAD

**Issue by fredrikburmester** [nextcloud/nextcloud-snap#623]
Hi, 

I'm trying to set up a cron job for previewgenerator. But I need the path to occ. Like this: 

`crontab -e -u cloud` cloud is the current user

`15    *  *  *  * php -f /var/www/nextcloud/occ preview:pre-generate` is the cron job

But I need to change the path and I don't know where occ is located. 

Right now i found occ in several places including `/snap/nextcloud/current/bin/occ` in root.
And `/snap/bin/nextcloud.occ` in user cloud

Please help.

 Thank you!

**Comment by kyrofa** [comment]
You want the one in `/snap/bin/nextcloud.occ`.

**Comment by fredrikburmester** [comment]
And the rest looked fine? Because I'm not seeing anything being outputted in my server.

**Comment by kyrofa** [comment]
Yeah you'll want something like this:

```
15 * * * * /snap/bin/nextcloud.occ preview:pre-generate
```

Regarding sending email and stuff, have you read through articles like [this one](15 * * * * php -f /var/www/nextcloud/occ preview:pre-generate)? I'll go ahead and close this issue since I think the question has been answered, but feel free to continue commenting on it.
