### ISSUE TITLE
No space left for NC - trying to expand HD

### ISSUE THREAD

**Issue by fredrikburmester** [nextcloud/nextcloud-snap#635]
I'm trying to expand the vdi of my ubuntu VM in VirtualBox because my Nextcloud is not working because i don't have enough space left. I've followed this tutorial:

[Youtube tutorial](https://www.youtube.com/watch?v=r_UyKufXR3c)

I'm stuck at the step where I should disable the swap files and make sure ubuntu uses the unallocated space. [06:32 in the video]. 

This is how it looks for me. 

[Image of my ubuntu partitions](https://imgur.com/a/cCyVxQb)

Can anyone help me from here? Thank you!

**Comment by r4co0n** [comment]
GParted is also able to expand partitions, and that's what you want to do here.

Expand the extended partion /dev/sda2 and the underlying logical partition /dev/sda5 to take up the remaining space. Reboot into the original OS,

Then, because you are using LVM, use `pvresize /dev/sda5` to make the LVM physical volume(PV) grow as large as it can.

Now you still have no more space available in your fs, but I can't tell you how to continue because I have no idea what your LVM logical volumes(LV) look like. You should have free space in your PV right now and can assign it to a LV, there are plenty of tutorials around for that, it's a one-liner.

**Comment by r4co0n** [comment]
On another note, this has nothing to do with the snap package of Nextcloud, so I'm closing this.

I'm still willing to help you, just comment on the closed issue.
