### ISSUE TITLE
Add license section to readme

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#68]
We have to make it clear that there are 2 types of licenses which come with the Snap:
1. This work of packaging Nextcloud and its required stack in a Snap is licensed under the GPL 3.0
2. Every component comes with its own license. Nextcloud, per example, is licensed under the AGPL3+

I have already modified the license in the store to AGPL3+ since it's the most restrictive one, but since there doesn't seem to be a way to show the license of every part of a Snap, we should include license files within each directory and mention them in the readme.

**Comment by camilasan** [comment]
I am not sure if this is directly related but why the license displayed is "proprietary"? (see https://github.com/nextcloud/client/issues/272)

**Comment by vrms** [comment]
+1 for adding license information to the snap, so that with `snap info nextcloud` the license section is not marked as "unset".

I personally believe that the Nextcloud license is what matters, not so much the license of packaging NC as a snap package (in case only one licensing information can be added to the snap info)

**Comment by kyrofa** [comment]
```
$ snap info nextcloud
<snip>
license:   AGPL-3.0+
<snip>
```

I think that's all that's really needed here.
