### ISSUE TITLE
Preview generator app does not generate previews in case of mass data migration

### ISSUE THREAD

**Issue by ovals12** [nextcloud/nextcloud-snap#684]
I am not sure if this is an issue in Preview Generator or NextCloud itself but I noticed Preview Generator app (https://github.com/rullzer/previewgenerator) does not pre-generate any previews after you import a bunch of images by copying them directly to data folder and executing `nextcloud.occ files:scan --all`
Basically the files are imported to NextCloud, you would also find them in GUI but preview-generator ignores them. 

I am not sure if this is the root cause but I noticed **after copying of files and executing `nextcloud.occ files:scan --all` there are no entries created in oc_activity table** although uploading files via Webdav or GUI upload will create entries there.

More details can be found here: https://github.com/rullzer/previewgenerator/issues/124

**Comment by kyrofa** [comment]
Either way, this does not sound like an issue with the snap. Seems that you already have a bug logged against the app, you can consider logging one against [nextcloud itself](https://github.com/nextcloud/server) as well, if you like. I'll go ahead and close this one unless you find that it's somehow due to the snap itself.
