### ISSUE TITLE
Is e2e working in the snap version?

### ISSUE THREAD

**Issue by Pantar2205** [nextcloud/nextcloud-snap#699]
Is e2e encryption supported in the snap version.
I can get as far as installing the e2e app, but it never shows up in Settings>Encryption as a module to be selected.

**Comment by pachulo** [comment]
I've just tried it and it's not something you are going to see as a module in the nextcloud config @Pantar2205 : Once the app is installed you need to use a compatible client, like the App for Android, to encrypt a folder. I did and uploaded a file and I can only access it from my phone.
It seems that the changes to make it work with the desktop application are underway, because I can neither access it from my computer.
