### ISSUE TITLE
Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by nyaasuki** [nextcloud/nextcloud-snap#728]
snap install nextcloud
error: cannot communicate with server: Post http://localhost/v2/snaps/nextcloud: dial unix /run/snapd.socket: connect: connection refused

......why

**Comment by kyrofa** [comment]
You say this is Xenial, but can you give me more information about how Xenial is installed? Native install? Cloud provider (which one)? Docker (snapd doesn't run in docker which would explain that error)?

**Comment by bellu** [comment]
Same issue here:

sudo snap install nextcloud

error: cannot communicate with server: Post http://localhost/v2/snaps/nextcloud: dial unix /run/snapd.socket: connect: connection refused

I'm using Ubuntu 16.04.3 on a VM in VirtualBox.

**Comment by sketchygamesdev** [comment]
@bellu @shimakazeDivine Howdy ya'll! Can you try the following commands:

First:
```
sudo systemctl restart snapd.service
```
Next: 
```
systemctl status snapd.service
```
and see if you get anything for the service itself. This will detail if snapd actually has processes running etc.

Also, depending on your setup, networking can be a little tricky. Are you running other services on 80 or 443 that would  be hanging on to the ports? That error is usually caused because the port is busy with another process or whatnot. I'm the dummy around here lol. Haven't been up to speed on coding in a while but I'm getting back at it!

**Comment by kyrofa** [comment]
> Also, depending on your setup, networking can be a little tricky. Are you running other services on 80 or 443 that would be hanging on to the ports? That error is usually caused because the port is busy with another process or whatnot.

Not quite-- you were correct earlier, this sounds like the snapd service simply isn't running. Without that, the Nextcloud snap doesn't run at all, so port contention won't be an issue.

I, too, would like to see the output of `systemctl status snapd.service`, and I'll add `journalctl -n100 -u snapd.service` as well.

**Comment by shimakazeDivine** [comment]
Thank you for the reply,I reset the server,

systemctl status snapd.service

root@niconi:~# systemctl status snapd.service
* snapd.service - Snappy daemon
   Loaded: loaded (/lib/systemd/system/snapd.service; static; vendor preset: enabled)
   Active: active (running) since Tue 2018-09-25 12:58:30 UTC; 6s ago
 Main PID: 657 (snapd)
    Tasks: 6 (limit: 512)
   CGroup: /system.slice/snapd.service
           `-657 /usr/lib/snapd/snapd

Sep 25 12:58:30 niconi /usr/lib/snapd/snapd[657]: daemon.go:202: DEBUG: adding /v2/icons/{name}/icon
Sep 25 12:58:30 niconi /usr/lib/snapd/snapd[657]: daemon.go:202: DEBUG: adding /v2/snaps
Sep 25 12:58:30 niconi /usr/lib/snapd/snapd[657]: daemon.go:202: DEBUG: adding /v2/snaps/{name}
Sep 25 12:58:30 niconi /usr/lib/snapd/snapd[657]: daemon.go:202: DEBUG: adding /v2/interfaces
Sep 25 12:58:30 niconi /usr/lib/snapd/snapd[657]: daemon.go:202: DEBUG: adding /v2/assertions
Sep 25 12:58:30 niconi /usr/lib/snapd/snapd[657]: daemon.go:202: DEBUG: adding /v2/assertions/{assertTyp
Sep 25 12:58:30 niconi /usr/lib/snapd/snapd[657]: daemon.go:202: DEBUG: adding /v2/events
Sep 25 12:58:30 niconi /usr/lib/snapd/snapd[657]: daemon.go:202: DEBUG: adding /v2/changes/{id}
Sep 25 12:58:30 niconi /usr/lib/snapd/snapd[657]: daemon.go:202: DEBUG: adding /v2/changes
Sep 25 12:58:30 niconi /usr/lib/snapd/snapd[657]: daemon.go:192: DEBUG: init done in 12.112375ms
lines 1-18/18 (END)


snap install nextcloud
error: cannot perform the following tasks:
- Mount snap "ubuntu-core" ([start snap-ubuntu\x2dcore-1797.mount] failed with exit status 1: Job for snap-ubuntu\x2dcore-1797.mount failed. See "systemctl status "snap-ubuntu\\x2dcore-1797.mount"" and "journalctl -xe" for details.
)


I made a new error.but i think this is the fault of service providers

**Comment by kyrofa** [comment]
You still haven't answered my original question, which is: how is this installed/where is it running? I'm starting to think you're on a cloud provider who gives you a non-standard kernel. They're likely breaking the law by calling it Ubuntu.

**Comment by sketchygamesdev** [comment]
@shimakazeDivine Are you running Ubuntu inside some kinds of container? LXD container? That looks like an LXD container's output...

> You still haven't answered my original question, which is: how is this installed/where is it running? I'm starting to think you're on a cloud provider who gives you a non-standard kernel. They're likely breaking the law by calling it Ubuntu.

@kyrofa I would take that bet with you and agree that it's probably a part of a container cluster in a cloud service...lets see what the next reply is.

**Comment by shimakazeDivine** [comment]
I looked at server virtualization,is LXC
Service provider : hostsolutions
I activated a  cheap storage VPS,but It's hard to use....

**Comment by kyrofa** [comment]
Sounds like you need another host with a suitable kernel, I'm sorry.
