### ISSUE TITLE
Question: Roadmap to v14

### ISSUE THREAD

**Issue by stone212** [nextcloud/nextcloud-snap#780]
This is not an issue but a question.  Is there a location where the roadmap for the snap is documented?   So if a user is interested in a feature that is in NextCloud he can guess when it might be available in the snap?  In this case I mean v14 of Nextcloud brought to the snap.  I do not mean to say you should rush development.  I am only curious if there is a way to alert users when the uprade may happen.  If there is not then that is the answer.

**Comment by pachulo** [comment]
I would say there is not a place where you can find it, but it's al scattered around different issues and PRs. 

As I understand, the problem here is that we depend on nextcloud upstream releasing fixes for issues that are affecting/“more prominent in” the snap, so without more people like @kyrofa contributing upstream and pushing for changes that affect us, the update rhythm is uncertain.
