### ISSUE TITLE
Missing icons on v14 RC1

### ISSUE THREAD

**Issue by benclark06** [nextcloud/nextcloud-snap#807]
Hey,
Some icons on the files app are missing on the sidebar
![image](https://user-images.githubusercontent.com/33701263/49688310-d0ba1900-fb07-11e8-8ad6-a828dc0a91ec.png)
The dev console shows a bunch of 404s
![image](https://user-images.githubusercontent.com/33701263/49688326-0ced7980-fb08-11e8-8d82-ad0a15d93fb4.png)
https://gist.github.com/benclark06/cc939a3ecb5541db821ec4302fd49e15
Are there any fixes for this?
This seems to be exclusively on the snap as it works just fine on docker.

**Comment by kyrofa** [comment]
Yeah this is an upstream bug we're working on: https://github.com/nextcloud/server/issues/12290 .

**Comment by benclark06** [comment]
Ok, thanks 👍

**Comment by kyrofa** [comment]
The fix is [proposed upstream](https://github.com/nextcloud/server/pull/13224).

**Comment by kyrofa** [comment]
The fix has landed. While waiting for it to be contained in a release, please take `14/edge` for a spin to make sure there aren't any other issues:

    $ sudo snap install nextcloud --channel=14/edge

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=14/edge

**Comment by bn4t** [comment]
Took it for a spin. Everything seems to work fine.

There is a warning that the PHP memory limit is below the recommended 512 MB. 
Will this be "fixed" or left unchanged since the snap is also for smaller devices?

**Comment by kyrofa** [comment]
It'll be [fixed once the PR for v14 lands](https://github.com/nextcloud/nextcloud-snap/pull/799/files#diff-74f6028f1effba5c37d82091e882e3a3R3) (which will be 14.0.5, looks like, once it's released). However, note that it will only be fixed for new installs: old installs will continue to use the old value, otherwise things might suddenly start crashing. Of course admins can always update that.

**Comment by pachulo** [comment]
Solved in the stable channel.
