### ISSUE TITLE
Move PHP extensions sub-routine to its own plugin

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#89]
It's far from ideal to have to recompile PHP every time we want to introduce and test a new PHP extension. It can easily add 10-30 minutes of compilation time, depending on the hardware, slowing down the development process.

Since the plugin would have to know where php has been compiled, I guess we would have to introduce a variable giving the name of the part responsible to compile PHP and to make sure it runs after PHP has been compiled

**Comment by kyrofa** [comment]
You must be on some old hardware... building PHP for me takes about a minute :stuck_out_tongue: . While this is a fine idea in theory, in practice it violates Snapcraft's part isolation, which means it will not be reliable. I'm afraid there's no good way to do this. Even if we re-wrote the config files to point to stage instead of installdir, the part containing the module would end up installing straight to stage instead of its own installdir, which also won't work correctly.

**Comment by oparoz** [comment]
Well, sure, if you add some cores and always compile the same PHP, but that's not been my experience when using a single core and adding features :(. And there are more issues like downloading the same PHP package over and over when going through the trial and error phase.

In any case, you're right, it would violate Snapcraft's part isolation, so forkers will have to choose what's best for them: Use a Makefile/plugin for extensions or wait longer.
