### ISSUE TITLE
Group/Shared Folder Delete issue in 15.0.2 -> 15.0.4

### ISSUE THREAD

**Issue by S1M0N** [nextcloud/nextcloud-snap#895]
Hi All, 

There seems to be a pretty major issue in 15.0.2, that carries through to 15.0.4 as well, on the main server build of NextCloud. This has to do with being unable to delete files from Group or Shared folders and there being a number of issues that come up when trying to do so. 

One user ( see https://github.com/nextcloud/server/issues/13380 ) seems to have come up with a "resolution" (read workaround) to this by deleting the `apps/encryption` folder, thus removing the NextCloud Default Encryption module. While this is obviously a pretty harsh resolution, it does seem to work. However there is no way to do this on snap, as the way snap works prevents this (read-only file system mountings that can't be remounted). 

Would it be possible to generate a 15.0.4 build of snap with the `apps/encryption` folder removed so that it doesn't load? This would allow testing on the snap build, but also work around the issue for the time being until a proper resolution is found. 

Alternatively, is there a way to go back to a pre-15 version of snap, as that was working?

Thanks,
Simon

**Comment by kyrofa** [comment]
Some folks use the encryption app, so no, we can't just remove it (that would remove it for everyone). You're welcome to build your own snap with the encryption app filtered out (it's easy, we do it for [one app already](https://github.com/nextcloud/nextcloud-snap/blob/master/snap/snapcraft.yaml#L171)) for testing purposes, but I'm afraid that solution doesn't work for the snap as a whole. Nextcloud needs to fix this issue.

As far as reverting back to v14, you might be able to but v15 was released a while ago, which means you'd lose any database modifications you made since then. To see if you can do it, run:

```
$ snap list nextcloud --all
Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  14.0.6snap1  11130  stable    nextcloud✓  disabled
nextcloud  15.0.2snap2  11336  stable    nextcloud✓  disabled
nextcloud  15.0.4snap1  11688  stable    nextcloud✓  -
```
 You'll see that, while on 15.0.4, I still have a v14 snap installed available for rollback. If I wanted to revert back to it, I'd run `sudo snap revert --revision=11130`. That won't touch any of your raw data, but it will put you back on the database you were using at that point in time, losing anything you've done recently. If you decide to go for that, after running that command I suggest running `sudo snap refresh nextcloud --channel=14` to switch channels away from `stable` (which will update you to v15 once an update is released) to `14` which will never try to give you a v15 snap.

**Comment by kyrofa** [comment]
I'm going to go ahead and close this issue since I think the question is answered, but feel free to continue discussion here.
