### ISSUE TITLE
TLS problem 15.0.5snap2

### ISSUE THREAD

**Issue by Des10101** [nextcloud/nextcloud-snap#950]
Hi, I understand the latest snap release has removed support for TLS1.0 in the interests of security but we have a problem in that our clients are not web browsers but are hard coded devices using TLS1.0 (security is not an issue for us).

Is it possible for us to manually change the settings to re-enable TLS1.0? Alternatively, is it possible to roll-back from the latest point release? I'm aware of the "sudo snap revert nextcloud" command, but I believe that will roll us back all the way to V14, which we would rather not do. 

Thank you.

**Comment by kyrofa** [comment]
Happy to support that, but before we discuss how, let's get you back up and running. Can you run `snap list nextcloud --all`, please?

**Comment by Des10101** [comment]
Hi kyrofa, thanks for quick response, here are the results

Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  15.0.4snap1  11688  stable    nextcloud✓  disabled
nextcloud  15.0.5snap1  11891  stable    nextcloud✓  disabled
nextcloud  15.0.5snap2  12387  stable    nextcloud✓  -

**Comment by kyrofa** [comment]
Ah you should be able to `snap revert` just fine, it'll revert to 11891 which is still 15.0.5. However, you won't get anything from 15.0.5snap2, including the security update to PHP. Would you prefer if I published a temporary branch with just the cipher update reverted?

**Comment by Des10101** [comment]
As long as we can revert then we should be fine, so I wont put you to any trouble. We can rollout patches to our clients that update TLS. Many thanks for your help.

**Comment by kyrofa** [comment]
Ah, you can update your devices to use TLS 1.2? That would be ideal. If you need the snap to support TLS 1.0, though, just shout and we'll figure something out.

**Comment by kyrofa** [comment]
@Des10101 I'm going to go ahead and close this, but I want to double check that you're in a good situation. My understanding of the issue is that you've reverted and have patched your clients to support a newer TLS, therefore I have no current plans to do anything on my end. If that doesn't match your understanding, say so and I'll reopen and we'll continue discussing.

A quick heads up: 15.0.7 is about to be released so even if you reverted you'll be updating soon. Just want to make sure you're in a good spot.

**Comment by Des10101** [comment]
I can confirm that we are all sorted thanks. Many thanks for your help and concern.
