### ISSUE TITLE
Questions about the nextcloud snap

### ISSUE THREAD

**Issue by hrishim** [nextcloud/nextcloud-snap#992]
Hello

This is not an issue but a set of questions so that I can understand nextcloud-snap better. I saw a non-issue  discussion thread in the git issues for this project and assumed it was ok to ask questions. Apologies if that is not OK. Please point me to an alternate place, if there is one. 

Thank you for making the nextcloud-snap. I installed it following a simple howto and it "just works". Well until I started trying other things. I have very little knowledge of snaps, so some of the stuff below may be grossly incorrect. Please bear with me

1. The nextcloud snap installs nextcloud, apache, Redis, and MySQL in a LXD container. Does this mean that all these applications are in (the same) a chroot and cannot access data outside ? If chrooted, what is the path of the root - is it /var/snap ?

2. Will the snap automatically update itself when the next version of this snap is released? Or do I have to update snap like I do other packages ?

3. So this snap installs apache and its listening on ports 80 and 443 like usual. If I want to serve other webpages (other than nextcloud), can I use the same apache instance? If yes, how do I do that ? For example, say I want to install iRedMail 

4. After installing the nextcloud snap I installed fail2ban on the same machine. But apache log files are not in /var/log. Is it possible to allow applications outside the snap (i.e. lxd container) access the logs of applications inside?

5. All /snap/bin/nextcloud.* point to /usr/bin/snap. Why have different links, all pointing to the same executable?
Edit: surprisingly /snap/bin/nextcloud.cc -h and /usr/bin/snap -h produce different outputs!! So I'm confused

Thanks
Hrishi

**Comment by kyrofa** [comment]
> I saw a non-issue discussion thread in the git issues for this project and assumed it was ok to ask questions.

You assumed correctly, asking questions here is just fine.

> 1. The nextcloud snap installs nextcloud, apache, Redis, and MySQL in a LXD container. Does this mean that all these applications are in (the same) a chroot and cannot access data outside ? If chrooted, what is the path of the root - is it /var/snap ?

This doesn't involve LXD at all-- snaps are their own thing. They don't have their own hard drives or their own network, they have YOUR hard drive and YOUR network. They are, however, confined from accessing both willy nilly. The data this particular snap accesses is in `/var/snap/nextcloud/{current,common}`, and if you connect the `removable-media` interface, you extend the confinement such that it can also access `/media/` and `/mnt/`.

> 2. Will the snap automatically update itself when the next version of this snap is released? Or do I have to update snap like I do other packages ?

All snaps update automatically, just sit back and relax.

> 3. So this snap installs apache and its listening on ports 80 and 443 like usual. If I want to serve other webpages (other than nextcloud), can I use the same apache instance? If yes, how do I do that ? For example, say I want to install iRedMail

Think of this snap as a standalone product that happens to serve by default on port 80 (and 443, if you enable HTTPS). Ignore the fact that it uses apache-- it might switch to nginx at some point. These are implementation details, and are not intended for use outside the snap (and in fact, since the config is read-only, it's pretty much impossible). If you want to host more than the snap on there, install your own webserver etc., request [the snap use different ports](https://github.com/nextcloud/nextcloud-snap#httphttps-port-configuration), and then proxy to it.

> 4. After installing the nextcloud snap I installed fail2ban on the same machine. But apache log files are not in /var/log. Is it possible to allow applications outside the snap (i.e. lxd container) access the logs of applications inside?

Look around in `/var/snap/nextcloud/current/`, you'll see all the logs (including Apache). **However**, I don't guarantee that those logs won't move on subsequent updates, so be aware.

> 5. All /snap/bin/nextcloud.* point to /usr/bin/snap. Why have different links, all pointing to the same executable? Edit: surprisingly /snap/bin/nextcloud.cc -h and /usr/bin/snap -h produce different outputs!! So I'm confused

This is a snapd implementation detail. Symlinks pointing to the same executable still provide the executable with the information necessary to do different things (i.e. the name of the symlink). Try this experiment to see how this works:

```
$ cat << 'EOF' > test.sh
#!/bin/sh
echo "hello, I'm $0"
EOF

$ chmod a+x test.sh
$ ln -s test.sh link
$ ./test.sh
hello, I'm ./test.sh
$ ./link
hello, I'm ./link
```

**Comment by kyrofa** [comment]
I believe this question has been answered, so I'll go and close this, but feel free to continue discussion here.

**Comment by hrishim** [comment]
Hello Kyle,

Thank you for the quick and detailed reply. I understand that the snap is
to be treated like a standalone application even though it is not. But it
will auto-update and require less (or no ?) maintenance compared to a stand
alone manual installation. Also, its a lot easier to install.

To support more than one snap  you suggested running the snaps on different
ports and installing a websever and then "proxying to" the webserver.

I am not familiar with how to do that. But based on some initial reading I
am guessing this would be configuring the webserver as a  reverse proxy? Is
that correct?

If not, could you suggest what I should search for/read-up to learn more on
how to setup so that I can have multiple snaps on the same machine.

Thanks
Hrishi
