### ISSUE TITLE
how to manually edit the config.php file?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/nextcloud-snap#995]
I installed nextcloud snap on ubuntu core 18 for raspberry pi3,

I would like to manually edit the config.php file located in
"/var/snap/nextcloud/current/nextcloud/config/config.php" 

via a snap editor see pinano or nano.
but when I try to access the config.php file it always gives me permission errors. 

how do you log in with these snaps? do you have other solutions?

**Comment by MarinMikael** [comment]
Hello,
I am not a dev, from my experience using NextCloud-snap on a rpi3 using Raspbian 9, those files belongs to root and can be edited given you have the right privileges.

**Comment by kyrofa** [comment]
Have you read the [README](https://github.com/nextcloud/nextcloud-snap/#configuration)? The writable config file is `/var/snap/nextcloud/current/nextcloud/config/config.php`.

**Comment by tigernero79** [comment]
unfortunately I don't find a wiki that explains how to log in root to modify the config.php or similar file.

I use ubuntu core 18 and I installed the nextcloud snap.

Is there an easy way to log in as root?

I connect in ssh with ubuntu one credentials.

what text editor software can you use knowing you can only install snap packages that enable me editing privileges?

**Comment by tigernero79** [comment]
I tried also with 
`sudo -i `
I go to root mode but I always have permission denied if I use pinano editor

**Comment by robertgarrigos** [comment]
Please, reopen this issue because the issue still applies. It's not enough to edit the config.php file as root as @kyrofa suggested (and then closed the issue) because the file is unwritable. This is: is there a way to edit the config file? If there is, please, open the issue and let's find the answer. It there is not then somebody say so. Thanks.

**Comment by kyrofa** [comment]
> It's not enough to edit the config.php file as root as @kyrofa suggested (and then closed the issue) because the file is unwritable.

`/var/snap/nextcloud/current/nextcloud/config/config.php` is certainly writable, but it's owned by root. You need to use sudo or otherwise gain root privileges to edit it. The one in `/snap/nextcloud/current/` is indeed not writable, but that's okay, it's not the one that's used anyway. Take careful note of the path you're using.

**Comment by robertgarrigos** [comment]
Thanks @kyrofa you are right and I was wrong. I was provably looking at the wrong file.
